import { LyricLine } from './types';

// Replace with real API data when integrating the backend.
export const MOCK_LYRICS: LyricLine[] = [
  {
    id: 0,
    japanese: '公園の落ち葉が舞って',
    romaji: 'Kouen no ochiba ga matte',
    english: 'The fallen leaves in the park are dancing',
    vocab: [
      { word: '公園', reading: 'こうえん', meaning: ['park', 'public park'], jlpt: 'N4', is_common: true },
      { word: '落ち葉', reading: 'おちば', meaning: ['fallen leaves', 'dead leaves'], jlpt: null, is_common: true },
      { word: '舞う', reading: 'まう', meaning: ['to dance', 'to flutter', 'to swirl'], jlpt: null, is_common: true },
    ],
    kanji: [
      { kanji: '公', onyomi: ['コウ', 'ク'], kunyomi: ['おおやけ'], meaning: 'public, official', jlpt: 'N4' },
      { kanji: '園', onyomi: ['エン'], kunyomi: ['その'], meaning: 'garden, park, orchard', jlpt: 'N4' },
      { kanji: '落', onyomi: ['ラク'], kunyomi: ['お.ちる', 'お.とす'], meaning: 'fall, drop, come down', jlpt: 'N3' },
      { kanji: '葉', onyomi: ['ヨウ'], kunyomi: ['は', '-ば'], meaning: 'leaf, word', jlpt: 'N3' },
      { kanji: '舞', onyomi: ['ブ', 'マイ'], kunyomi: ['ま.う', 'ま.い'], meaning: 'dance, flutter', jlpt: null },
    ],
  },
  {
    id: 1,
    japanese: '飛び方を教えてくれている',
    romaji: 'Tobikata wo oshiete kurete iru',
    english: 'Teaching me how to fly',
    vocab: [
      { word: '飛ぶ', reading: 'とぶ', meaning: ['to fly', 'to jump', 'to leap'], jlpt: 'N4', is_common: true },
      { word: '教える', reading: 'おしえる', meaning: ['to teach', 'to tell', 'to inform'], jlpt: 'N5', is_common: true },
      { word: 'くれる', reading: 'くれる', meaning: ['to give (to me)', 'to do for me'], jlpt: 'N4', is_common: true },
    ],
    kanji: [
      { kanji: '飛', onyomi: ['ヒ'], kunyomi: ['と.ぶ', 'と.ばす'], meaning: 'fly, leap, skip', jlpt: 'N4' },
      { kanji: '方', onyomi: ['ホウ'], kunyomi: ['かた', '-かた', '-がた'], meaning: 'direction, person, way', jlpt: 'N5' },
      { kanji: '教', onyomi: ['キョウ'], kunyomi: ['おし.える', 'おそ.わる'], meaning: 'teach, instruct', jlpt: 'N5' },
    ],
  },
  {
    id: 2,
    japanese: '親切にどうも',
    romaji: 'Shinsetsu ni doumo',
    english: 'How very kind of you',
    vocab: [
      { word: '親切', reading: 'しんせつ', meaning: ['kindness', 'kind', 'gentle'], jlpt: 'N4', is_common: true },
      { word: 'どうも', reading: 'どうも', meaning: ['thank you', 'somehow', 'very'], jlpt: 'N4', is_common: true },
    ],
    kanji: [
      { kanji: '親', onyomi: ['シン'], kunyomi: ['おや', 'した.しい', 'した.しむ'], meaning: 'parent, intimate, close', jlpt: 'N4' },
      { kanji: '切', onyomi: ['セツ', 'サイ'], kunyomi: ['き.る', 'き.れる'], meaning: 'cut, sever, urgent', jlpt: 'N4' },
    ],
  },
  {
    id: 3,
    japanese: '僕もそんなふうに 軽やかでいられたら',
    romaji: 'Boku mo sonna fuu ni karoyaka de iraretara',
    english: 'If only I could be that light and free too',
    vocab: [
      { word: '僕', reading: 'ぼく', meaning: ['I', 'me (male)'], jlpt: 'N4', is_common: true },
      { word: 'そんな', reading: 'そんな', meaning: ['such', 'that kind of', 'like that'], jlpt: 'N5', is_common: true },
      { word: '軽やか', reading: 'かろやか', meaning: ['light', 'nimble', 'airy'], jlpt: null, is_common: true },
      { word: 'いる', reading: 'いる', meaning: ['to be', 'to exist', 'to stay'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '僕', onyomi: ['ボク'], kunyomi: ['しもべ'], meaning: 'I, me (male)', jlpt: 'N4' },
      { kanji: '軽', onyomi: ['ケイ'], kunyomi: ['かる.い', 'かろ.やか'], meaning: 'light, easygoing', jlpt: 'N3' },
    ],
  },
  {
    id: 4,
    japanese: '横切ったネコに',
    romaji: 'Yokogitta neko ni',
    english: 'To a cat that crossed my path',
    vocab: [
      { word: '横切る', reading: 'よこぎる', meaning: ['to cross', 'to cut across', 'to traverse'], jlpt: null, is_common: true },
      { word: 'ネコ', reading: 'ねこ', meaning: ['cat'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '横', onyomi: ['オウ'], kunyomi: ['よこ'], meaning: 'sideways, side, horizontal', jlpt: 'N3' },
      { kanji: '切', onyomi: ['セツ', 'サイ'], kunyomi: ['き.る', 'き.れる'], meaning: 'cut, sever, urgent', jlpt: 'N4' },
    ],
  },
  {
    id: 5,
    japanese: '不安を打ち明けながら',
    romaji: 'Fuan wo uchiakenagara',
    english: 'While confessing my worries',
    vocab: [
      { word: '不安', reading: 'ふあん', meaning: ['anxiety', 'unease', 'worry'], jlpt: 'N3', is_common: true },
      { word: '打ち明ける', reading: 'うちあける', meaning: ['to confess', 'to open up', 'to be candid'], jlpt: null, is_common: true },
    ],
    kanji: [
      { kanji: '不', onyomi: ['フ', 'ブ'], kunyomi: [''], meaning: 'un-, not, negative', jlpt: 'N4' },
      { kanji: '安', onyomi: ['アン'], kunyomi: ['やす.い', 'やす.まる', 'やす'], meaning: 'relax, cheap, ease', jlpt: 'N4' },
      { kanji: '打', onyomi: ['ダ', 'ダース'], kunyomi: ['う.つ', 'う.ち-', 'うち'], meaning: 'strike, hit, knock', jlpt: 'N3' },
      { kanji: '明', onyomi: ['メイ', 'ミョウ', 'ミン'], kunyomi: ['あ.かり', 'あか.るい', 'あ.ける'], meaning: 'bright, light, reveal', jlpt: 'N4' },
    ],
  },
  {
    id: 6,
    japanese: 'あぁ 君に会いたくなる',
    romaji: 'Aa kimi ni aitaku naru',
    english: 'Ah, I start wanting to see you',
    vocab: [
      { word: 'あぁ', reading: 'あぁ', meaning: ['ah', 'oh', 'alas'], jlpt: null, is_common: true },
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '会う', reading: 'あう', meaning: ['to meet', 'to see', 'to encounter'], jlpt: 'N4', is_common: true },
      { word: 'なる', reading: 'なる', meaning: ['to become', 'to get', 'to turn'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '会', onyomi: ['カイ', 'エ'], kunyomi: ['あ.う', 'あ.わせる'], meaning: 'meeting, meet, come together', jlpt: 'N4' },
    ],
  },
  {
    id: 7,
    japanese: 'どんな言葉が 願いが 景色が',
    romaji: 'Donna kotoba ga negai ga keshiki ga',
    english: 'What words, what wishes, what scenery',
    vocab: [
      { word: 'どんな', reading: 'どんな', meaning: ['what kind of', 'what sort of'], jlpt: 'N5', is_common: true },
      { word: '言葉', reading: 'ことば', meaning: ['word', 'language', 'expression'], jlpt: 'N4', is_common: true },
      { word: '願い', reading: 'ねがい', meaning: ['wish', 'desire', 'prayer'], jlpt: 'N3', is_common: true },
      { word: '景色', reading: 'けしき', meaning: ['scenery', 'scene', 'landscape'], jlpt: 'N3', is_common: true },
    ],
    kanji: [
      { kanji: '言', onyomi: ['ゲン', 'ゴン'], kunyomi: ['い.う', 'こと'], meaning: 'say, word, speech', jlpt: 'N4' },
      { kanji: '葉', onyomi: ['ヨウ'], kunyomi: ['は', '-ば'], meaning: 'leaf, word', jlpt: 'N3' },
      { kanji: '願', onyomi: ['ガン'], kunyomi: ['ねが.う', '-ねが.い'], meaning: 'petition, wish, hope', jlpt: 'N3' },
      { kanji: '景', onyomi: ['ケイ'], kunyomi: [''], meaning: 'scenery, view, condition', jlpt: 'N3' },
      { kanji: '色', onyomi: ['ショク', 'シキ'], kunyomi: ['いろ'], meaning: 'color, kind, appearance', jlpt: 'N5' },
    ],
  },
  {
    id: 8,
    japanese: '君を笑顔に幸せにするだろう',
    romaji: 'Kimi wo egao ni shiawase ni suru darou',
    english: 'Would make you smile and be happy',
    vocab: [
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '笑顔', reading: 'えがお', meaning: ['smiling face', 'smile'], jlpt: 'N3', is_common: true },
      { word: '幸せ', reading: 'しあわせ', meaning: ['happiness', 'fortune', 'luck'], jlpt: 'N4', is_common: true },
      { word: 'する', reading: 'する', meaning: ['to do', 'to make', 'to cause'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '笑', onyomi: ['ショウ'], kunyomi: ['わら.う', 'え.む'], meaning: 'laugh, smile', jlpt: 'N4' },
      { kanji: '顔', onyomi: ['ガン'], kunyomi: ['かお'], meaning: 'face, expression', jlpt: 'N4' },
      { kanji: '幸', onyomi: ['コウ'], kunyomi: ['さいわ.い', 'さち', 'しあわ.せ'], meaning: 'happiness, good luck', jlpt: 'N3' },
    ],
  },
  {
    id: 9,
    japanese: '地図なんかないけど',
    romaji: 'Chizu nanka nai kedo',
    english: "I don't have a map or anything like that",
    vocab: [
      { word: '地図', reading: 'ちず', meaning: ['map', 'atlas'], jlpt: 'N4', is_common: true },
      { word: 'ない', reading: 'ない', meaning: ['not exist', 'to not have', 'nonexistent'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '地', onyomi: ['チ', 'ジ'], kunyomi: [''], meaning: 'ground, earth, land', jlpt: 'N4' },
      { kanji: '図', onyomi: ['ズ', 'ト'], kunyomi: ['はか.る'], meaning: 'map, diagram, plan', jlpt: 'N4' },
    ],
  },
  {
    id: 10,
    japanese: '歩いて探して',
    romaji: 'Aruite sagashite',
    english: 'Walking and searching',
    vocab: [
      { word: '歩く', reading: 'あるく', meaning: ['to walk', 'to go on foot'], jlpt: 'N5', is_common: true },
      { word: '探す', reading: 'さがす', meaning: ['to search for', 'to look for', 'to seek'], jlpt: 'N3', is_common: true },
    ],
    kanji: [
      { kanji: '歩', onyomi: ['ホ', 'ブ', 'フ'], kunyomi: ['ある.く', 'あゆ.む'], meaning: 'walk, step, pace', jlpt: 'N5' },
      { kanji: '探', onyomi: ['タン'], kunyomi: ['さが.す', 'さぐ.る'], meaning: 'search, seek, look for', jlpt: 'N3' },
    ],
  },
  {
    id: 11,
    japanese: '君に渡せたらいい',
    romaji: 'Kimi ni watasetara ii',
    english: 'I hope I can give it to you',
    vocab: [
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '渡す', reading: 'わたす', meaning: ['to hand over', 'to give', 'to pass'], jlpt: 'N3', is_common: true },
      { word: 'いい', reading: 'いい', meaning: ['good', 'fine', 'okay'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '渡', onyomi: ['ト'], kunyomi: ['わた.る', 'わた.す'], meaning: 'transit, cross, hand over', jlpt: 'N3' },
    ],
  },
  {
    id: 12,
    japanese: '偶然と運命の違いは',
    romaji: 'Guuzen to unmei no chigai wa',
    english: 'The difference between coincidence and fate',
    vocab: [
      { word: '偶然', reading: 'ぐうぜん', meaning: ['coincidence', 'chance', 'by accident'], jlpt: 'N3', is_common: true },
      { word: '運命', reading: 'うんめい', meaning: ['fate', 'destiny', 'lot'], jlpt: 'N3', is_common: true },
      { word: '違い', reading: 'ちがい', meaning: ['difference', 'distinction', 'discrepancy'], jlpt: 'N3', is_common: true },
    ],
    kanji: [
      { kanji: '偶', onyomi: ['グウ'], kunyomi: ['たま', 'たま.たま'], meaning: 'accidentally, even number', jlpt: 'N3' },
      { kanji: '然', onyomi: ['ゼン', 'ネン'], kunyomi: ['しか', 'しか.り', 'しか.し'], meaning: 'but, however, nature', jlpt: 'N4' },
      { kanji: '運', onyomi: ['ウン'], kunyomi: ['はこ.ぶ'], meaning: 'carry, luck, fate', jlpt: 'N4' },
      { kanji: '命', onyomi: ['メイ', 'ミョウ'], kunyomi: ['いのち'], meaning: 'life, fate, command', jlpt: 'N3' },
      { kanji: '違', onyomi: ['イ'], kunyomi: ['ちが.う', 'ちが.い', 'ちが.える'], meaning: 'differ, wrong, mistake', jlpt: 'N3' },
    ],
  },
  {
    id: 13,
    japanese: '君の顔に書いてあって',
    romaji: 'Kimi no kao ni kaite atte',
    english: "It's written on your face",
    vocab: [
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '顔', reading: 'かお', meaning: ['face', 'expression', 'look'], jlpt: 'N4', is_common: true },
      { word: '書く', reading: 'かく', meaning: ['to write', 'to compose', 'to draw'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '顔', onyomi: ['ガン'], kunyomi: ['かお'], meaning: 'face, expression', jlpt: 'N4' },
      { kanji: '書', onyomi: ['ショ'], kunyomi: ['か.く', '-が.き', '-がき'], meaning: 'write, book, document', jlpt: 'N5' },
    ],
  },
  {
    id: 14,
    japanese: '人生の意味はいつか君がくれた',
    romaji: 'Jinsei no imi wa itsuka kimi ga kureta',
    english: 'The meaning of life — you gave it to me once',
    vocab: [
      { word: '人生', reading: 'じんせい', meaning: ['life', 'human life', 'one\'s life'], jlpt: 'N3', is_common: true },
      { word: '意味', reading: 'いみ', meaning: ['meaning', 'significance', 'sense'], jlpt: 'N4', is_common: true },
      { word: 'いつか', reading: 'いつか', meaning: ['sometime', 'someday', 'one day'], jlpt: 'N4', is_common: true },
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: 'くれる', reading: 'くれる', meaning: ['to give (to me)', 'to do for me'], jlpt: 'N4', is_common: true },
    ],
    kanji: [
      { kanji: '人', onyomi: ['ジン', 'ニン'], kunyomi: ['ひと', '-り', '-と'], meaning: 'person, people', jlpt: 'N5' },
      { kanji: '生', onyomi: ['セイ', 'ショウ'], kunyomi: ['い.きる', 'う.まれる', 'なま'], meaning: 'life, birth, genuine', jlpt: 'N5' },
      { kanji: '意', onyomi: ['イ'], kunyomi: [''], meaning: 'idea, mind, heart, thought', jlpt: 'N3' },
      { kanji: '味', onyomi: ['ミ'], kunyomi: ['あじ', 'あじ.わう'], meaning: 'flavor, taste, meaning', jlpt: 'N4' },
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
    ],
  },
  {
    id: 15,
    japanese: 'アメの中に入ってた',
    romaji: 'Ame no naka ni haitteta',
    english: 'It was inside a piece of candy',
    vocab: [
      { word: 'アメ', reading: 'あめ', meaning: ['candy', 'sweets', 'lozenge'], jlpt: null, is_common: true },
      { word: '中', reading: 'なか', meaning: ['inside', 'middle', 'among'], jlpt: 'N5', is_common: true },
      { word: '入る', reading: 'はいる', meaning: ['to enter', 'to go in', 'to be contained'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '中', onyomi: ['チュウ', 'ジュウ'], kunyomi: ['なか', 'うち'], meaning: 'middle, inside, center', jlpt: 'N5' },
      { kanji: '入', onyomi: ['ニュウ', 'ジュ'], kunyomi: ['い.る', 'い.れる', 'はい.る'], meaning: 'enter, insert, contain', jlpt: 'N5' },
    ],
  },
  {
    id: 16,
    japanese: '君の周りに浮かんだものに触れて',
    romaji: 'Kimi no mawari ni ukanda mono ni furete',
    english: 'Reaching out to touch the things floating around you',
    vocab: [
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '周り', reading: 'まわり', meaning: ['surroundings', 'around', 'vicinity'], jlpt: 'N3', is_common: true },
      { word: '浮かぶ', reading: 'うかぶ', meaning: ['to float', 'to rise to surface', 'to come to mind'], jlpt: 'N3', is_common: true },
      { word: 'もの', reading: 'もの', meaning: ['thing', 'object', 'matter'], jlpt: 'N5', is_common: true },
      { word: '触れる', reading: 'ふれる', meaning: ['to touch', 'to feel', 'to come in contact'], jlpt: 'N3', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '周', onyomi: ['シュウ', 'シュ'], kunyomi: ['まわ.り'], meaning: 'circumference, lap, around', jlpt: 'N3' },
      { kanji: '浮', onyomi: ['フ'], kunyomi: ['う.く', 'う.かぶ', 'う.かれる'], meaning: 'float, rise to surface', jlpt: 'N2' },
      { kanji: '触', onyomi: ['ショク'], kunyomi: ['ふ.れる', 'さわ.る'], meaning: 'contact, touch, feel', jlpt: 'N2' },
    ],
  },
  {
    id: 17,
    japanese: 'あぁ 何を作れるだろう',
    romaji: 'Aa nani wo tsukureru darou',
    english: 'Ah, what can I create',
    vocab: [
      { word: 'あぁ', reading: 'あぁ', meaning: ['ah', 'oh', 'alas'], jlpt: null, is_common: true },
      { word: '何', reading: 'なに', meaning: ['what', 'how many'], jlpt: 'N5', is_common: true },
      { word: '作る', reading: 'つくる', meaning: ['to make', 'to create', 'to produce'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '何', onyomi: ['カ'], kunyomi: ['なに', 'なん'], meaning: 'what, how many', jlpt: 'N5' },
      { kanji: '作', onyomi: ['サク', 'サ'], kunyomi: ['つく.る'], meaning: 'make, create, work', jlpt: 'N5' },
    ],
  },
  {
    id: 18,
    japanese: 'どれも些細で 頼りない決意で',
    romaji: 'Dore mo sasai de tayorinai ketsui de',
    english: 'All of it trivial, with unreliable resolve',
    vocab: [
      { word: 'どれ', reading: 'どれ', meaning: ['which', 'which one', 'any'], jlpt: 'N4', is_common: true },
      { word: '些細', reading: 'ささい', meaning: ['trivial', 'trifling', 'petty'], jlpt: null, is_common: false },
      { word: '頼りない', reading: 'たよりない', meaning: ['unreliable', 'helpless', 'weak'], jlpt: null, is_common: false },
      { word: '決意', reading: 'けつい', meaning: ['determination', 'resolution', 'resolve'], jlpt: 'N2', is_common: true },
    ],
    kanji: [
      { kanji: '些', onyomi: ['サ'], kunyomi: ['ちょっと'], meaning: 'a little, trifling', jlpt: null },
      { kanji: '細', onyomi: ['サイ'], kunyomi: ['ほそ.い', 'ほそ.る', 'こま.かい'], meaning: 'thin, slender, detail', jlpt: 'N3' },
      { kanji: '頼', onyomi: ['ライ'], kunyomi: ['たの.む', 'たの.もしい', 'たよ.る'], meaning: 'depend on, trust, request', jlpt: 'N3' },
      { kanji: '決', onyomi: ['ケツ'], kunyomi: ['き.める', 'き.まる', 'さ.く'], meaning: 'decide, determine, resolve', jlpt: 'N4' },
      { kanji: '意', onyomi: ['イ'], kunyomi: [''], meaning: 'idea, mind, heart, thought', jlpt: 'N3' },
    ],
  },
  {
    id: 19,
    japanese: '僕の世界の模様はできてる',
    romaji: 'Boku no sekai no moyou wa dekiteru',
    english: "My world's pattern is taking shape",
    vocab: [
      { word: '僕', reading: 'ぼく', meaning: ['I', 'me (male)'], jlpt: 'N4', is_common: true },
      { word: '世界', reading: 'せかい', meaning: ['world', 'society', 'the universe'], jlpt: 'N4', is_common: true },
      { word: '模様', reading: 'もよう', meaning: ['pattern', 'design', 'state of affairs'], jlpt: 'N2', is_common: true },
      { word: 'できる', reading: 'できる', meaning: ['to be able to', 'to form', 'to be made'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '僕', onyomi: ['ボク'], kunyomi: ['しもべ'], meaning: 'I, me (male)', jlpt: 'N4' },
      { kanji: '世', onyomi: ['セイ', 'セ', 'ソウ'], kunyomi: ['よ', '-よ'], meaning: 'generation, world, society', jlpt: 'N4' },
      { kanji: '界', onyomi: ['カイ'], kunyomi: [''], meaning: 'world, boundary, limits', jlpt: 'N4' },
      { kanji: '模', onyomi: ['モ', 'ボ'], kunyomi: [''], meaning: 'imitate, pattern, copy', jlpt: 'N2' },
      { kanji: '様', onyomi: ['ヨウ'], kunyomi: ['さま', '-さま', 'さん'], meaning: 'manner, way, style', jlpt: 'N3' },
    ],
  },
  {
    id: 20,
    japanese: 'お洒落ではないけど 唯一のダサさで',
    romaji: 'Oshare de wa nai kedo yuiitsu no dasa-sa de',
    english: "Not stylish, but with a one-of-a-kind uncoolness",
    vocab: [
      { word: 'お洒落', reading: 'おしゃれ', meaning: ['fashionable', 'stylish', 'chic'], jlpt: null, is_common: true },
      { word: 'ない', reading: 'ない', meaning: ['not exist', 'to not have', 'nonexistent'], jlpt: 'N5', is_common: true },
      { word: '唯一', reading: 'ゆいいつ', meaning: ['only', 'sole', 'unique'], jlpt: 'N2', is_common: true },
    ],
    kanji: [
      { kanji: '洒', onyomi: ['シャ', 'サイ', 'セン'], kunyomi: ['そそ.ぐ'], meaning: 'rinse, sprinkle, stylish', jlpt: null },
      { kanji: '落', onyomi: ['ラク'], kunyomi: ['お.ちる', 'お.とす'], meaning: 'fall, drop, come down', jlpt: 'N3' },
      { kanji: '唯', onyomi: ['ユイ', 'イ'], kunyomi: ['ただ'], meaning: 'solely, only, merely', jlpt: null },
      { kanji: '一', onyomi: ['イチ', 'イツ'], kunyomi: ['ひと-', 'ひと.つ'], meaning: 'one, single, alone', jlpt: 'N5' },
    ],
  },
  {
    id: 21,
    japanese: '君が笑えたらいい',
    romaji: 'Kimi ga waraetara ii',
    english: 'I hope it makes you smile',
    vocab: [
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '笑う', reading: 'わらう', meaning: ['to laugh', 'to smile', 'to grin'], jlpt: 'N4', is_common: true },
      { word: 'いい', reading: 'いい', meaning: ['good', 'fine', 'okay'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '笑', onyomi: ['ショウ'], kunyomi: ['わら.う', 'え.む'], meaning: 'laugh, smile', jlpt: 'N4' },
    ],
  },
  {
    id: 22,
    japanese: '僕の中のキミ キミの中の僕',
    romaji: 'Boku no naka no kimi kimi no naka no boku',
    english: 'You inside me, me inside you',
    vocab: [
      { word: '僕', reading: 'ぼく', meaning: ['I', 'me (male)'], jlpt: 'N4', is_common: true },
      { word: '中', reading: 'なか', meaning: ['inside', 'middle', 'within'], jlpt: 'N5', is_common: true },
      { word: 'キミ', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '僕', onyomi: ['ボク'], kunyomi: ['しもべ'], meaning: 'I, me (male)', jlpt: 'N4' },
      { kanji: '中', onyomi: ['チュウ', 'ジュウ'], kunyomi: ['なか', 'うち'], meaning: 'middle, inside, center', jlpt: 'N5' },
    ],
  },
  {
    id: 23,
    japanese: 'きっと同じじゃないけど',
    romaji: 'Kitto onaji ja nai kedo',
    english: "Surely not the same, but",
    vocab: [
      { word: 'きっと', reading: 'きっと', meaning: ['surely', 'certainly', 'definitely'], jlpt: 'N4', is_common: true },
      { word: '同じ', reading: 'おなじ', meaning: ['same', 'identical', 'equal'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '同', onyomi: ['ドウ'], kunyomi: ['おな.じ'], meaning: 'same, agree, equal', jlpt: 'N4' },
    ],
  },
  {
    id: 24,
    japanese: '駅前のパン屋と踏切の閉まる音',
    romaji: 'Ekimae no pan\'ya to fumikiri no shimaru oto',
    english: 'The station bakery and the sound of the crossing gate closing',
    vocab: [
      { word: '駅前', reading: 'えきまえ', meaning: ['in front of the station', 'near the station'], jlpt: null, is_common: true },
      { word: 'パン屋', reading: 'ぱんや', meaning: ['bakery', 'bread shop'], jlpt: null, is_common: true },
      { word: '踏切', reading: 'ふみきり', meaning: ['railroad crossing', 'level crossing'], jlpt: null, is_common: true },
      { word: '閉まる', reading: 'しまる', meaning: ['to close', 'to shut', 'to be closed'], jlpt: 'N4', is_common: true },
      { word: '音', reading: 'おと', meaning: ['sound', 'noise', 'note'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '駅', onyomi: ['エキ'], kunyomi: [''], meaning: 'station, post', jlpt: 'N5' },
      { kanji: '前', onyomi: ['ゼン'], kunyomi: ['まえ', '-まえ'], meaning: 'in front, before, previous', jlpt: 'N5' },
      { kanji: '屋', onyomi: ['オク'], kunyomi: ['や', 'ね'], meaning: 'roof, house, shop', jlpt: 'N4' },
      { kanji: '踏', onyomi: ['トウ'], kunyomi: ['ふ.む', 'ふ.まえる'], meaning: 'step, trample, walk on', jlpt: 'N2' },
      { kanji: '閉', onyomi: ['ヘイ'], kunyomi: ['と.じる', 'と.ざす', 'し.める', 'し.まる'], meaning: 'closed, shut, close', jlpt: 'N3' },
      { kanji: '音', onyomi: ['オン', 'イン'], kunyomi: ['おと', 'ね'], meaning: 'sound, noise', jlpt: 'N5' },
    ],
  },
  // ── Chorus repeat ──
  {
    id: 25,
    japanese: 'あぁ 君に会いたくなる',
    romaji: 'Aa kimi ni aitaku naru',
    english: 'Ah, I start wanting to see you',
    vocab: [
      { word: 'あぁ', reading: 'あぁ', meaning: ['ah', 'oh', 'alas'], jlpt: null, is_common: true },
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '会う', reading: 'あう', meaning: ['to meet', 'to see', 'to encounter'], jlpt: 'N4', is_common: true },
      { word: 'なる', reading: 'なる', meaning: ['to become', 'to get', 'to turn'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '会', onyomi: ['カイ', 'エ'], kunyomi: ['あ.う', 'あ.わせる'], meaning: 'meeting, meet, come together', jlpt: 'N4' },
    ],
  },
  {
    id: 26,
    japanese: 'どんな言葉が 願いが 景色が',
    romaji: 'Donna kotoba ga negai ga keshiki ga',
    english: 'What words, what wishes, what scenery',
    vocab: [
      { word: 'どんな', reading: 'どんな', meaning: ['what kind of', 'what sort of'], jlpt: 'N5', is_common: true },
      { word: '言葉', reading: 'ことば', meaning: ['word', 'language', 'expression'], jlpt: 'N4', is_common: true },
      { word: '願い', reading: 'ねがい', meaning: ['wish', 'desire', 'prayer'], jlpt: 'N3', is_common: true },
      { word: '景色', reading: 'けしき', meaning: ['scenery', 'scene', 'landscape'], jlpt: 'N3', is_common: true },
    ],
    kanji: [
      { kanji: '言', onyomi: ['ゲン', 'ゴン'], kunyomi: ['い.う', 'こと'], meaning: 'say, word, speech', jlpt: 'N4' },
      { kanji: '葉', onyomi: ['ヨウ'], kunyomi: ['は', '-ば'], meaning: 'leaf, word', jlpt: 'N3' },
      { kanji: '願', onyomi: ['ガン'], kunyomi: ['ねが.う', '-ねが.い'], meaning: 'petition, wish, hope', jlpt: 'N3' },
      { kanji: '景', onyomi: ['ケイ'], kunyomi: [''], meaning: 'scenery, view, condition', jlpt: 'N3' },
      { kanji: '色', onyomi: ['ショク', 'シキ'], kunyomi: ['いろ'], meaning: 'color, kind, appearance', jlpt: 'N5' },
    ],
  },
  {
    id: 27,
    japanese: '君を笑顔に幸せにするだろう',
    romaji: 'Kimi wo egao ni shiawase ni suru darou',
    english: 'Would make you smile and be happy',
    vocab: [
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '笑顔', reading: 'えがお', meaning: ['smiling face', 'smile'], jlpt: 'N3', is_common: true },
      { word: '幸せ', reading: 'しあわせ', meaning: ['happiness', 'fortune', 'luck'], jlpt: 'N4', is_common: true },
      { word: 'する', reading: 'する', meaning: ['to do', 'to make', 'to cause'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '笑', onyomi: ['ショウ'], kunyomi: ['わら.う', 'え.む'], meaning: 'laugh, smile', jlpt: 'N4' },
      { kanji: '顔', onyomi: ['ガン'], kunyomi: ['かお'], meaning: 'face, expression', jlpt: 'N4' },
      { kanji: '幸', onyomi: ['コウ'], kunyomi: ['さいわ.い', 'さち', 'しあわ.せ'], meaning: 'happiness, good luck', jlpt: 'N3' },
    ],
  },
  {
    id: 28,
    japanese: '地図なんかないけど',
    romaji: 'Chizu nanka nai kedo',
    english: "I don't have a map or anything like that",
    vocab: [
      { word: '地図', reading: 'ちず', meaning: ['map', 'atlas'], jlpt: 'N4', is_common: true },
      { word: 'ない', reading: 'ない', meaning: ['not exist', 'to not have', 'nonexistent'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '地', onyomi: ['チ', 'ジ'], kunyomi: [''], meaning: 'ground, earth, land', jlpt: 'N4' },
      { kanji: '図', onyomi: ['ズ', 'ト'], kunyomi: ['はか.る'], meaning: 'map, diagram, plan', jlpt: 'N4' },
    ],
  },
  {
    id: 29,
    japanese: '歩いて探して',
    romaji: 'Aruite sagashite',
    english: 'Walking and searching',
    vocab: [
      { word: '歩く', reading: 'あるく', meaning: ['to walk', 'to go on foot'], jlpt: 'N5', is_common: true },
      { word: '探す', reading: 'さがす', meaning: ['to search for', 'to look for', 'to seek'], jlpt: 'N3', is_common: true },
    ],
    kanji: [
      { kanji: '歩', onyomi: ['ホ', 'ブ', 'フ'], kunyomi: ['ある.く', 'あゆ.む'], meaning: 'walk, step, pace', jlpt: 'N5' },
      { kanji: '探', onyomi: ['タン'], kunyomi: ['さが.す', 'さぐ.る'], meaning: 'search, seek, look for', jlpt: 'N3' },
    ],
  },
  {
    id: 30,
    japanese: '君に渡せたらいい',
    romaji: 'Kimi ni watasetara ii',
    english: 'I hope I can give it to you',
    vocab: [
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '渡す', reading: 'わたす', meaning: ['to hand over', 'to give', 'to pass'], jlpt: 'N3', is_common: true },
      { word: 'いい', reading: 'いい', meaning: ['good', 'fine', 'okay'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '渡', onyomi: ['ト'], kunyomi: ['わた.る', 'わた.す'], meaning: 'transit, cross, hand over', jlpt: 'N3' },
    ],
  },
  {
    id: 31,
    japanese: '道のりと時間を 花束に変えて',
    romaji: 'Michinori to jikan wo hanataba ni kaete',
    english: 'Turning the distance and time into a bouquet of flowers',
    vocab: [
      { word: '道のり', reading: 'みちのり', meaning: ['distance', 'journey', 'the road ahead'], jlpt: null, is_common: true },
      { word: '時間', reading: 'じかん', meaning: ['time', 'hour', 'hours'], jlpt: 'N5', is_common: true },
      { word: '花束', reading: 'はなたば', meaning: ['bouquet', 'bunch of flowers'], jlpt: null, is_common: true },
      { word: '変える', reading: 'かえる', meaning: ['to change', 'to alter', 'to transform'], jlpt: 'N4', is_common: true },
    ],
    kanji: [
      { kanji: '道', onyomi: ['ドウ', 'トウ'], kunyomi: ['みち'], meaning: 'road, path, way', jlpt: 'N4' },
      { kanji: '時', onyomi: ['ジ'], kunyomi: ['とき', '-どき'], meaning: 'time, hour, moment', jlpt: 'N5' },
      { kanji: '間', onyomi: ['カン', 'ケン'], kunyomi: ['ま', 'あいだ', 'あい'], meaning: 'interval, space, between', jlpt: 'N5' },
      { kanji: '花', onyomi: ['カ', 'ケ'], kunyomi: ['はな'], meaning: 'flower, blossom', jlpt: 'N5' },
      { kanji: '束', onyomi: ['ソク'], kunyomi: ['たば', 'つか', 'たば.ねる'], meaning: 'bundle, bunch, control', jlpt: 'N3' },
      { kanji: '変', onyomi: ['ヘン'], kunyomi: ['か.わる', 'か.える'], meaning: 'change, strange, unusual', jlpt: 'N4' },
    ],
  },
  {
    id: 32,
    japanese: '君に渡せたらいい',
    romaji: 'Kimi ni watasetara ii',
    english: 'I hope I can give it to you',
    vocab: [
      { word: '君', reading: 'きみ', meaning: ['you', 'ruler'], jlpt: 'N5', is_common: true },
      { word: '渡す', reading: 'わたす', meaning: ['to hand over', 'to give', 'to pass'], jlpt: 'N3', is_common: true },
      { word: 'いい', reading: 'いい', meaning: ['good', 'fine', 'okay'], jlpt: 'N5', is_common: true },
    ],
    kanji: [
      { kanji: '君', onyomi: ['クン'], kunyomi: ['きみ'], meaning: 'you, ruler, lord', jlpt: 'N5' },
      { kanji: '渡', onyomi: ['ト'], kunyomi: ['わた.る', 'わた.す'], meaning: 'transit, cross, hand over', jlpt: 'N3' },
    ],
  },
];
